#!/bin/bash
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install bash-completion jq apt-utils whiptail nano
rm logitechmediaserver*.deb
rm servers.json
wget --no-check-certificate https://lms-community.github.io/lms-server-repository/servers.json
deb=$(jq -r '.latest.deb.url' servers.json)
wget --no-check-certificate "$deb"
sudo apt -y install ./logitechmediaserver*.deb
if [ $(grep -c "Start LMS" /support/startSSHServer.sh) -eq 0 ]
then
  echo '## Start LMS ##' >> /support/startSSHServer.sh
  echo 'nohup bash /home/userland/startlms.sh &' >> /support/startSSHServer.sh
  echo '#!/bin/bash' > /home/userland/startlms.sh
  echo 'service logitechmediaserver start' >> /home/userland/startlms.sh
  echo 'dropbearpid=$(cat /run/dropbear.pid)' >> /home/userland/startlms.sh
  echo 'lmspid=$(cat /run/logitechmediaserver.pid)' >> /home/userland/startlms.sh
  echo 'echo "$dropbearpid $lmspid" > /run/dropbear.pid' >> /home/userland/startlms.sh
fi
sudo service logitechmediaserver start
dropbearpid=$(cat /run/dropbear.pid)
lmspid=$(cat /run/logitechmediaserver.pid)
sudo echo "$dropbearpid $lmspid" > /run/dropbear.pid
