#!/bin/sh
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install bash-completion jq apt-utils whiptail
rm logitechmediaserver*.deb
rm servers.json
wget https://lms-community.github.io/lms-server-repository/servers.json
deb=$(jq '."8.4.0".deb.url' servers.json)
wget $deb
sudo apt -y install ./logitechmediaserver*.deb
if [ $(grep -c "Starting LMS" /support/startSSHServer.sh) -eq 0 ]
then
  echo '## Starting LMS ##' >> /support/startSSHServer.sh
  echo 'pkill --signal 9 squeezeboxserv' >> /support/startSSHServer.sh
  echo 'pkill --signal 9 logger' >> /support/startSSHServer.sh
  echo 'pkill --signal 9 perl' >> /support/startSSHServer.sh
  echo 'service logitechmediaserver start' >> /support/startSSHServer.sh
fi
sudo service logitechmediaserver start
