#!/bin/bash
cd ~
if [ ! -d '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian' ]; then
  echo "deb https://grimler.se/termux-packages-24 stable main" > $PREFIX/etc/apt/sources.list
  echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" >> $PREFIX/etc/apt/sources.list
  apt update
  apt upgrade -y -o Dpkg::Options::="--force-confnew"
  apt install -y -o Dpkg::Options::="--force-confnew" proot proot-distro wget squeezelite || pkg --check-mirror install -y -o Dpkg::Options::="--force-confnew" proot proot-distro wget squeezelite
  termux-setup-storage
  proot-distro install debian
fi
if [ $(grep -c "allow-external-apps=true" ~/.termux/termux.properties) -eq 0 ]; then
  echo "allow-external-apps=true" >> ~/.termux/termux.properties
fi

rm installlms
rm .lmsinstalled
rm .materialinstalled

cat <<EOF > installlms
#!/bin/bash
if [  ! -d '/usr/share/squeezeboxserver' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install bash-completion jq apt-utils whiptail nano wget tree
  rm logitechmediaserver*.deb
  rm servers.json
  wget https://lms-community.github.io/lms-server-repository/servers.json
  wget \$(jq -r '."8.4.1".deb.url' servers.json)
  apt -y install ./logitechmediaserver*.deb
  touch .lmsfirstinstall
fi
if [  ! -d '/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install libxml2-utils
  rm extensions.xml
  wget https://lms-community.github.io/lms-plugin-repository/extensions.xml -O extensions.xml
  wget \$(xmllint --xpath 'string(//extensions/plugins/plugin[@name="MaterialSkin"]/@url)' extensions.xml) -O material.zip
  rm -rf MaterialSkin
  mkdir MaterialSkin
  unzip material.zip -d MaterialSkin
  rm material.zip
  mkdir -p /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  mv MaterialSkin /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  mkdir -p /var/lib/squeezeboxserver/prefs/
  chown -R squeezeboxserver:nogroup /var/lib/squeezeboxserver/
  echo "wizardDone: 1" > /var/lib/squeezeboxserver/prefs/server.prefs
  echo "skin: material" >> /var/lib/squeezeboxserver/prefs/server.prefs
  touch .materialfirstinstall
fi
EOF

cat <<EOF > updatelms
#!/bin/bash
rm logitechmediaserver*.deb
rm servers.json
error=""
wget https://lms-community.github.io/lms-server-repository/servers.json || error="ERROR: Can't get latest server details"
if [ -z "\$error" ]; then
  wget \$(jq -r '."8.4.1".deb.url' servers.json) || error="ERROR: Can't find latest server download"
  if [ -z "\$error" ]; then
    if [ $(apt show logitechmediaserver | grep ^Version: | cut -d' ' -f2) == $(ls logitechmediaserver* | cut -d'_' -f2) ]; then
      error="You already have the latest version"
    else
      apt -y install ./logitechmediaserver*.deb || error="ERROR: installation failed"
    fi
  fi
fi
echo "========================================"
if [ -z "\$error" ]; then
  echo "LMS updated"
  echo "Restart using your Termux 'Restart LMS' widget"
else
  echo \$error
  echo "LMS NOT updated"
fi
echo "Press Enter to close this terminal"
echo "========================================"
read
EOF

if [  ! -d ~/.shortcuts/tasks ]; then
  mkdir -p /data/data/com.termux/files/home/.shortcuts/tasks
  chmod 700 -R /data/data/com.termux/files/home/.shortcuts/tasks
  mkdir -p /data/data/com.termux/files/home/.shortcuts/icons
  chmod -R a-x,u=rwX,go-rwx /data/data/com.termux/files/home/.shortcuts/icons
fi

rm ~/.shortcuts/tasks/*
rm ~/.shortcuts/icons/*
rm ~/.shortcuts/*
curl https://raw.githubusercontent.com/darrell-k/slimserver-platforms/Android/Android/lms.png -o ~/.shortcuts/icons/"Restart LMS.png"
curl https://raw.githubusercontent.com/darrell-k/slimserver-platforms/Android/Android/lms-red.png -o ~/.shortcuts/icons/"Stop LMS.png"
echo "proot-distro login --termux-home --no-kill-on-exit debian -- service logitechmediaserver restart" > ~/.shortcuts/tasks/"Restart LMS"
chmod +x ~/.shortcuts/tasks/"Restart LMS"
echo "proot-distro login --termux-home debian -- service logitechmediaserver stop" > ~/.shortcuts/tasks/"Stop LMS"
chmod +x ~/.shortcuts/tasks/"Stop LMS"
echo "proot-distro login --termux-home debian -- bash updatelms" > ~/.shortcuts/"Update LMS"
chmod +x ~/.shortcuts/"Update LMS" 
proot-distro login --termux-home debian -- bash installlms

echo   "======================="
if [ -e .lmsfirstinstall ]; then
  echo "LMS installed"
  rm .lmsfirstinstall
fi
if [ -e .materialfirstinstall ]; then
  echo "Material Skin Installed"
  rm .materialfirstinstall
fi
echo "Scripts updated"
echo   "======================="
