#!/bin/bash
pkg upgrade
apt -y install proot proot-distro
termux-setup-storage
proot-distro install debian

cat <<EOF > installlms
#!/bin/bash
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install bash-completion jq apt-utils whiptail nano
rm logitechmediaserver*.deb
rm servers.json
wget --no-check-certificate https://lms-community.github.io/lms-server-repository/servers.json
deb=$(jq -r '.latest.deb.url' servers.json)
wget --no-check-certificate "$deb"
sudo apt -y install ./logitechmediaserver*.deb
EOF

proot-distro login --termux-home debian



