#!/bin/bash
if [ ! -d '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install proot proot-distro wget
  termux-setup-storage
  proot-distro install debian
fi
if [ $(grep -c "allow-external-apps=true" ~/.termux/termux.properties) -eq 0 ]; then
  apt -y -o Dpkg::Options::="--force-confnew" install squeezelite
  echo "allow-external-apps=true" >> ~/.termux/termux.properties
fi

rm installlms
cat <<EOF > installlms
#!/bin/bash
if [  ! -e '.lmsinstalled' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install bash-completion jq apt-utils whiptail nano wget tree init-system-helpers
  rm logitechmediaserver*.deb
  rm servers.json
  wget https://lms-community.github.io/lms-server-repository/servers.json
  wget \$(jq -r '."8.4.1".deb.url' servers.json)
  apt -y install ./logitechmediaserver*.deb
  touch .lmsinstalled
fi
if [  ! -e '.materialinstalled' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install libxml2-utils
  rm extensions.xml
  wget https://lms-community.github.io/lms-plugin-repository/extensions.xml -O extensions.xml
  wget \$(xmllint --xpath 'string(//extensions/plugins/plugin[@name="MaterialSkin"]/@url)' extensions.xml) -O material.zip
  rm -rf MaterialSkin
  mkdir MaterialSkin
  unzip material.zip -d MaterialSkin
  rm material.zip
  mkdir -p /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  mv MaterialSkin /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  chown -R squeezeboxserver:nogroup /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  touch .materialinstalled
  service logitechmediaserver start
  sleep 5
  service logitechmediaserver stop
fi
EOF
echo "service logitechmediaserver restart" > startlms
echo "bash" >> startlms
if [  ! -d '~/.shortcuts/tasks' ]; then
  mkdir -p /data/data/com.termux/files/home/.shortcuts/tasks
  chmod 700 -R /data/data/com.termux/files/home/.shortcuts/tasks
  mkdir -p /data/data/com.termux/files/home/.shortcuts/icons
  chmod -R a-x,u=rwX,go-rwx /data/data/com.termux/files/home/.shortcuts/icons
  curl https://raw.githubusercontent.com/darrell-k/slimserver-platforms/Android/Android/lms.png -o ~/.shortcuts/icons/lms.png
  echo "proot-distro login --termux-home debian -- bash startlms" > ~/.shortcuts/tasks/lms
  chmod +x ~/.shortcuts/tasks/lms
fi
proot-distro login --termux-home debian -- bash installlms
echo "===================="
echo "LMS is now installed"
echo "===================="




