#!/bin/bash
if [ ! -d '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian' ]; then
  pkg upgrade
  apt -y install proot proot-distro wget
  termux-setup-storage
  proot-distro install debian
fi

rm startlms
cat <<EOF > startlms
#!/bin/bash
if [  ! -e '.lmsinstalled' ]; then
  apt -y update
  apt -y upgrade
  apt -y install bash-completion jq apt-utils whiptail nano wget tree init-system-helpers
  rm logitechmediaserver*.deb
  rm servers.json
  wget https://lms-community.github.io/lms-server-repository/servers.json
  deb=\$(jq -r '.latest.deb.url' servers.json)
  wget "\$deb"
  apt -y install ./logitechmediaserver*.deb
  touch .lmsinstalled
fi
service logitechmediaserver start
bash
EOF

if [  ! -d '~/.shortcuts/tasks' ]; then
mkdir -p /data/data/com.termux/files/home/.shortcuts/tasks
chmod 700 -R /data/data/com.termux/files/home/.shortcuts/tasks
fi
cp lms ~/.shortcuts/tasks/
chmod +x ~/.shortcuts/tasks/lms
proot-distro login --termux-home debian -- bash startlms



