#!/bin/bash
if [ ! -d '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian' ]; then
  echo "deb https://grimler.se/termux-packages-24 stable main" > $PREFIX/etc/apt/sources.list
  echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" >> $PREFIX/etc/apt/sources.list
  apt update
  apt upgrade -y -o Dpkg::Options::="--force-confnew"
  apt install -y -o Dpkg::Options::="--force-confnew" proot proot-distro wget squeezelite || pkg --check-mirror install -y -o Dpkg::Options::="--force-confnew" proot proot-distro wget squeezelite
  termux-setup-storage
  proot-distro install debian
fi
if [ $(grep -c "allow-external-apps=true" ~/.termux/termux.properties) -eq 0 ]; then
  echo "allow-external-apps=true" >> ~/.termux/termux.properties
fi

rm installlms
rm .lmsinstalled
rm ,materialinstalled
cat <<EOF > installlms
#!/bin/bash
if [  ! -d '/usr/share/squeezeboxserver' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install bash-completion jq apt-utils whiptail nano wget tree init-system-helpers
  rm logitechmediaserver*.deb
  rm servers.json
  wget https://lms-community.github.io/lms-server-repository/servers.json
  wget \$(jq -r '."8.4.1".deb.url' servers.json)
  apt -y install ./logitechmediaserver*.deb
  touch .lmsfirstinstall
fi
if [  ! -d '/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin' ]; then
  apt update
  apt -y -o Dpkg::Options::="--force-confnew" upgrade
  apt -y -o Dpkg::Options::="--force-confnew" install libxml2-utils
  rm extensions.xml
  wget https://lms-community.github.io/lms-plugin-repository/extensions.xml -O extensions.xml
  wget \$(xmllint --xpath 'string(//extensions/plugins/plugin[@name="MaterialSkin"]/@url)' extensions.xml) -O material.zip
  rm -rf MaterialSkin
  mkdir MaterialSkin
  unzip material.zip -d MaterialSkin
  rm material.zip
  mkdir -p /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  mv MaterialSkin /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/
  mkdir -p /var/lib/squeezeboxserver/prefs/
  chown -R squeezeboxserver:nogroup /var/lib/squeezeboxserver/
  echo "wizardDone: 1" > /var/lib/squeezeboxserver/prefs/server.prefs
  echo "skin: material" >> /var/lib/squeezeboxserver/prefs/server.prefs
fi
EOF
if [  ! -d ~/.shortcuts/tasks ]; then
  mkdir -p /data/data/com.termux/files/home/.shortcuts/tasks
  chmod 700 -R /data/data/com.termux/files/home/.shortcuts/tasks
  mkdir -p /data/data/com.termux/files/home/.shortcuts/icons
  chmod -R a-x,u=rwX,go-rwx /data/data/com.termux/files/home/.shortcuts/icons
fi
if [  ! -e ~/.shortcuts/tasks/"Restart LMS" ]; then
  rm ~/.shortcuts/tasks/*
  rm ~/.shortcuts/icons/*
  curl https://raw.githubusercontent.com/darrell-k/slimserver-platforms/Android/Android/lms.png -o ~/.shortcuts/icons/"Restart LMS.png"
  curl https://raw.githubusercontent.com/darrell-k/slimserver-platforms/Android/Android/lms-red.png -o ~/.shortcuts/icons/"Stop LMS.png"
  echo "proot-distro login --termux-home debian -- service logitechmediaserver restart" > ~/.shortcuts/tasks/"Restart LMS"
  chmod +x ~/.shortcuts/tasks/"Restart LMS"
  echo "proot-distro login --termux-home debian -- service logitechmediaserver stop" > ~/.shortcuts/tasks/"Stop LMS"
  chmod +x ~/.shortcuts/tasks/"Stop LMS"
  touch .tasksinstalled
fi
proot-distro login --termux-home debian -- bash installlms
if [ -e .lmsfirstinstall ]; then
  text=installed
  rm .lmsfirstinstall
else
  text=updated
fi
echo "===================="
echo "LMS is now $text"
echo "===================="
