# logrotate configuration for Lyrion

# default to truncating log files
# Lyrion will fail if its log it deleted
copytruncate
# compress files
compress
# do not mail files
nomail
# file size before rotation
size 10M
# number of files to keep
rotate 4

# rotate everyting in /var/log using defaults
/logs/*.log {
}
