#!/bin/sh

PRODUCT_NAME=UEMusicLibrary
PREFPANE_TO="/Library/PreferencePanes/$PRODUCT_NAME.prefPane"

# remove the version file triggering the update prompt
if [ -e ~/Library/Caches/$PRODUCT_NAME/updates/server.version ] ; then
	rm -f ~/Library/Caches/$PRODUCT_NAME/updates/server.version
fi

if [ -e /Library/Caches/$PRODUCT_NAME/updates/server.version ] ; then
	rm -f /Library/Caches/$PRODUCT_NAME/updates/server.version
fi


if [ -e "$PREFPANE_TO" ] ; then
	cd "$PREFPANE_TO/Contents/server"

	# install SC to start at boot time if it hasn't been configured yet; update startupitem if we're updating
	if [ -e /Library/StartupItems/$PRODUCT_NAME ] ; then
		../Resources/create-startup.sh
	fi

	sudo -b -H -u $USER "../Resources/start-server.sh"

	cd "/Library/PreferencePanes/$PRODUCT_NAME.prefPane/Contents/server/Bin/darwin"

	osascript openprefs.scpt &

	exit 0
else
	exit 1
fi
