#!/bin/bash

SERVER_NAME=slimserver.pl

check_server() {
	ps -axw | grep $SERVER_NAME | grep -v grep | cut -d ' ' -f1 | cat
}

check_prefpane() {
	ps -axww | grep "System Preferences" | grep -v grep | cat
}

RESULT=$(check_server)
if [ "$RESULT" != "" ]; then
	kill -15 $RESULT
fi

for i in 1 2 3 4 5 6 7 8 9 10; do
	RESULT=$(check_server)
	if [ "$RESULT" = "" ]; then
		break
	fi
	sleep 1;
done

RESULT=$(check_server)
if [ "$RESULT" != "" ]; then
	osascript -e 'tell app "System Events" to display dialog "Please stop Logitech Media Server before running the installer." buttons { "Ok" } with title "Logitech Media Server" default button 1'
fi

RESULT=$(check_prefpane)
if [ "$RESULT" != "" ]; then
	osascript -e 'tell application "System Preferences" to quit'
fi

for i in 1 2 3 4 5 6 7 8 9 10; do
	RESULT=$(check_prefpane)
	if [ "$RESULT" = "" ]; then
		break
	fi
	sleep 1;
done

RESULT=$(check_prefpane)
if [ "$RESULT" != "" ]; then
	osascript -e 'tell app "System Events" to display dialog "Please quit System Preferences before running the installer." buttons { "Ok" } with title "Logitech Media Server" default button 1'
fi

for NAME in "Squeezebox Server", "Squeezebox"; do
	if [ -e "$HOME/Library/PreferencePanes/$NAME.prefPane" ]; then
		rm -rf "$HOME/Library/PreferencePanes/$NAME.prefPane" 2>&1
	fi
	
	if [ -e "/Library/PreferencePanes/$NAME.prefPane" ]; then
		rm -rf "/Library/PreferencePanes/$NAME.prefPane" 2>&1
	fi
done
